Repository prgrms-be-devcourse/NBE1_1_Team9, pull requests merged in 2024-09, with the labels that each got.

#9 [feat] querydsl을 이용한 동적쿼리 구현
  NBE1_1_9team-main/build.gradle
  NBE1_1_9team-main/src/main/java/gc/cafe/api/controller/product/ProductController.java
  NBE1_1_9team-main/src/main/java/gc/cafe/api/controller/product/request/ProductSearchRequest.java
  NBE1_1_9team-main/src/main/java/gc/cafe/api/service/product/ProductService.java
  NBE1_1_9team-main/src/main/java/gc/cafe/api/service/product/ProductServiceImpl.java
  NBE1_1_9team-main/src/main/java/gc/cafe/api/service/product/request/ProductSearchServiceRequest.java
  NBE1_1_9team-main/src/main/java/gc/cafe/config/QuerydslConfig.java
  NBE1_1_9team-main/src/main/java/gc/cafe/domain/product/CustomProductRepository.java
  NBE1_1_9team-main/src/main/java/gc/cafe/domain/product/CustomProductRepositoryImpl.java
  NBE1_1_9team-main/src/main/java/gc/cafe/domain/product/ProductRepository.java
  NBE1_1_9team-main/src/test/java/gc/cafe/api/service/product/ProductServiceImplTest.java
  NBE1_1_9team-main/src/test/java/gc/cafe/domain/product/CustomProductRepositoryImplTest.java
Labels: feature, 민혁

#8 #3 - 회원관리 구현
  NBE1_1_9team-main/build.gradle
  NBE1_1_9team-main/src/main/java/gc/cafe/api/controller/user/UserController.java
  NBE1_1_9team-main/src/main/java/gc/cafe/api/controller/user/request/JoinRequest.java
  NBE1_1_9team-main/src/main/java/gc/cafe/api/controller/user/request/LoginRequest.java
  NBE1_1_9team-main/src/main/java/gc/cafe/api/service/user/UserService.java
  NBE1_1_9team-main/src/main/java/gc/cafe/api/service/user/request/JoinServiceRequest.java
  NBE1_1_9team-main/src/main/java/gc/cafe/api/service/user/response/EmailResponse.java
  NBE1_1_9team-main/src/main/java/gc/cafe/api/service/user/response/UserIdResponse.java
  NBE1_1_9team-main/src/main/java/gc/cafe/config/RedisConfig.java
  NBE1_1_9team-main/src/main/java/gc/cafe/config/SecurityConfig.java
  NBE1_1_9team-main/src/main/java/gc/cafe/config/WebConfig.java
  NBE1_1_9team-main/src/main/java/gc/cafe/domain/user/User.java
  NBE1_1_9team-main/src/main/java/gc/cafe/domain/user/UserRepository.java
  NBE1_1_9team-main/src/main/java/gc/cafe/domain/user/UserRole.java
  NBE1_1_9team-main/src/main/java/gc/cafe/global/auth/error/JwtAccessDeniedHandler.java
  NBE1_1_9team-main/src/main/java/gc/cafe/global/auth/error/JwtAuthenticationEntryPoint.java
  NBE1_1_9team-main/src/main/java/gc/cafe/global/auth/filter/JwtAuthenticationProcessingFilter.java
  NBE1_1_9team-main/src/main/java/gc/cafe/global/auth/login/LoginService.java
  NBE1_1_9team-main/src/main/java/gc/cafe/global/auth/service/JwtService.java
  NBE1_1_9team-main/src/main/java/gc/cafe/global/dto/ErrorResponse.java
  NBE1_1_9team-main/src/main/java/gc/cafe/global/dto/TokenResponse.java
  NBE1_1_9team-main/src/main/java/gc/cafe/global/event/RefreshTokenEvent.java
  NBE1_1_9team-main/src/main/java/gc/cafe/global/event/RefreshTokenEventHandler.java
  NBE1_1_9team-main/src/main/java/gc/cafe/global/redis/RefreshToken.java
  NBE1_1_9team-main/src/main/java/gc/cafe/global/redis/RefreshTokenRepository.java
  NBE1_1_9team-main/src/main/resources/application.yaml
  NBE1_1_9team-main/src/test/java/gc/cafe/ControllerTestSupport.java
  NBE1_1_9team-main/src/test/java/gc/cafe/api/controller/order/OrderControllerTest.java
  NBE1_1_9team-main/src/test/java/gc/cafe/api/controller/product/ProductControllerTest.java
Labels: 🔥 매운맛, feature, 태호, backend

#7 Refactor/#4 refactor 코드 리팩토링, 라이브러리 설치
  front/package-lock.json
  front/package.json
  front/src/App.js
  front/src/App.jsx
  front/src/axios/BasicAxios.js
  front/src/components/Product.jsx
  front/src/components/ProductList.jsx
  front/src/components/Summary.jsx
  front/src/components/SummaryItem.jsx
  front/src/components/header/Header.jsx
  front/src/components/myorder/EmailForm.jsx
  front/src/components/myorder/Item.jsx
  front/src/components/myorder/Order.jsx
  front/src/components/myorder/Orders.jsx
  front/src/components/myorder/OrdersContiner.jsx
  front/src/page/ClientPage.jsx
  front/src/page/MyOrderPage.jsx
  front/src/page/OrderPage.jsx
  front/yarn.lock
Labels: 💧 순한맛, feature, fix, chore, 준호, refactor, frontend

#18 [Fix] #17 오류 수정
  front/README.md
  front/src/axios/BasicAxios.js
  front/src/components/Summary.jsx
  front/src/components/SummaryItem.jsx
  front/src/components/header/Header.jsx
  front/src/components/myorder/Orders.jsx
  front/src/components/user/UserContainer.jsx
  front/src/components/user/UserDiv.jsx
  front/src/context/UserContext.jsx
  front/src/page/LoginPage.jsx
  front/src/page/OrderPage.jsx
Labels: docs, fix, 준호, frontend
